version = 1
SPDX-PackageName = "roadmap"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/roadmap"

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    "CODEOWNERS",
    "CODE_OF_CONDUCT.md",
    "REUSE.toml"
    "scripts/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"
