name: Create Area Labels and Milestones Daily

on:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 06:00 CET / 07:00 CEST
  workflow_dispatch:

jobs:
  update-roadmap:
    name: Run Roadmap Updaters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate GH CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Add Labels Script
        run: scripts/create-area-labels.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Add Milestone Script
        run: scripts/create-milestone.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
